### ISSUE TITLE
[BUG] crashes on an invalid package.json

### ISSUE THREAD

**Issue by ljharb** [npm/read-package-json#108]
# What / Why
Try to run this package.json through read-package-json: https://github.com/browserify/resolve/blob/main/test/resolver/invalid_main/package.json

It crashes, with `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array` on the dirname call [here](https://github.com/npm/read-package-json/blob/main/read-json.js#L550).

To be clear, node crashes with the same error when trying to require this package fixture - but perhaps read-package-json should handle it a bit more gracefully?

In particular, it's not calling `cb` with an error - it's just throwing an uncaught error to the ether.

**Comment by ljharb** [comment]
No; node crashes when requiring the directory containing it as a package.json - ie, when trying to parse the main (just like in that test fixture)

**Comment by wraithgar** [comment]
`read-package-json@4.1.2`

**Comment by ljharb** [comment]
Thanks for the fast fix!
