### ISSUE TITLE
logger function in npmlog gets overwritten on npm install

### ISSUE THREAD

**Issue by robertkowalski** [npm/read-package-json#29]
Currently having a look on https://github.com/npm/read-package-json/issues/28

When I run `npm i ./foo` to test `normalize-package-data` which can handle the scripts-property and is logging them, it turns out that the log function from package.json gets changed from `addLocalDirectory` before npm-log can log the log message.

**Comment by lukekarrys** [comment]
Cleaning out old/outdated issues in this repo 👋🏼
