### ISSUE TITLE
make name / version optional

### ISSUE THREAD

**Issue by cowboy** [npm/read-package-json#3]
For projects that won't be published as npm modules, but that instead use npm only as a means for installing local dependencies (think of the package.json in this case like a Gemfile) the currently required `name` and `version` fields are unnecessary. It would be great if they were optional.

**Comment by muuvmuuv** [comment]
same goes for the readme field. Idk why it is passing the content of a hole markdown file into a string.

**Comment by wraithgar** [comment]
The name and version field really do need to be required at this time because otherwise npm has no way to know what's already in the tree when it comes time to update/install new deps.
