### ISSUE TITLE
Package readme is not being set, even though it exists in the directory.

### ISSUE THREAD

**Issue by OverZealous** [npm/read-package-json#31]
> I'm moving this from npm/npm#4585 to here because I think the issue might be within read-package-json.

---

> NOTE: The readme is showing up right now on this package do to the `globOpts.sync` hack I describe below.

---

I have an NPM package ([gulp-cdnizer](https://npmjs.org/package/gulp-cdnizer)) that I'm working on.  If I don't manually include the `readme` property in my `package.json`, then I get "ERROR: No README data found!" for the readme data.

I'm not doing anything funny with the `.npmignore`, and I don't actually understand how this is supposed to work.  I've manually updated the readme on the previous packages I've published, but in researching this, I realized I shouldn't have to do this.

Hopefully you can help.

versions:

``` plain
node: 0.10.25
npm:  1.3.25
read-package-json: 1.1.6
```

**Comment by giza182** [comment]
I'm having this issue in v 3.4.1 with a private package that I am writing.

**Comment by mpfdavis** [comment]
This problem is back, my readme just disappeared from outputcache, when i try the above hack i get callback provided to sync glob - i'm using v7.4.0 (npm v4.0.5)

**Comment by mpfdavis** [comment]
Hacked the function to be sync, I can see the file getting logged and in readme_ function, still doesn't appear on NPM.

**Comment by mpfdavis** [comment]
- ignore, appears NPM had an issue their side...
