### ISSUE TITLE
gitHead not populated if we operate out of a sub directory

### ISSUE THREAD

**Issue by jpnelson** [npm/read-package-json#66]
_Edit:_ [see my later comment for a better description of the issue](https://github.com/npm/read-package-json/issues/66#issuecomment-222036879)

Could we use something like

```
git rev-parse --show-toplevel
```

to find the directory? Otherwise, when publishing out of subdirectories, the git root isn't found.

Also: how would this be implemented? Running git directly?

**Comment by jpnelson** [comment]
I realise we couldn't run git directly because there may be no git installed... but if there are other suggestions around how to do this, I'm keen to here.

**Comment by jpnelson** [comment]
The problem is here: https://github.com/npm/read-package-json/blob/master/read-json.js#L293

**Comment by robertkowalski** [comment]
@jpnelson interesting find! so you say that you have on main directory A which is published and has a package.json file. in that directory A is another subdirectory B (node_modules?) which has an package.json file, too and you want to publish it from that subdirectory for convenience?

**Comment by jpnelson** [comment]
Yes – so this is my directory structure:

* repo/
  * .git/
  * package.json
  * components/
    * A/
      * package.json
    * B/
      * package.json

To publish package A, I run `npm publish components/A`

The problem is that `gitHead` doesn't get populated in the published npm package, because it seems npm looks for the `.git` folder next to the `A/package.json` file, rather than relative to the cwd, which is what I'd suggest it should do. That way, if you're publishing a package from a repo with multiple packages (I'm using [lerna](https://github.com/lerna/lerna) for that) you can still get the `gitHead` field form the published `package.json`.

**Comment by robertkowalski** [comment]
ah that makes sense! @npm/cli-team what do you think?

**Comment by robertkowalski** [comment]
@ashleygwilliams read your tweet about the weeklies today. this is not super critical for me, so i don't think i have to join the standup in the hope to change your direction of development. Nevertheless, I think this is a valid use case and question. Would it make sense to accept community contributions here or should we just close it and never think about it again?

**Comment by jpnelson** [comment]
@robertkowalski @ashleygwilliams what was the tweet? I'd be happy to provide more details on my use case if that would help.

**Comment by evocateur** [comment]
Since [`v3.0.0-beta.0`](https://github.com/lerna/lerna/releases/tag/v3.0.0-beta.0), `lerna` now injects the `gitHead` property before publishing to the registry.

**Comment by felixfbecker** [comment]
sourcegraph.com relies on `gitHead` to provide cross-repository go-to-definition. With monorepos becoming more popular, this is a big problem.
Can we just walk the directory tree upwards to find a `.git` folder? Should only be a few lines of code and negligible perf overhead.
