### ISSUE TITLE
2.0.7 breaks 0.10 & 0.12

### ISSUE THREAD

**Issue by strugee** [npm/read-package-json#71]
Commit 839b56e2b2343c68eb0be4fef5930842600a8194 uses an arrow function, which breaks on Node 0.10 and 0.12. That means it should've been semver-major, but wasn't.

I would suggest reverting this commit, publishing a patch release, unreverting, then publishing 3.0.0.

**Comment by iarna** [comment]
Or, you know, patching it.

**Comment by iarna** [comment]
Fixed in 2.0.10.

**Comment by strugee** [comment]
@iarna hah, that works too! Guess I should've actually done some thinking before making that suggestion :P

Thanks for the super quick fix!
