### ISSUE TITLE
path to package.json not reading correctly

### ISSUE THREAD

**Issue by dsc03** [npm/read-package-json#75]
Hi! I'm having an issue where the readJson method is not properly getting the right file path to my package.json. I have the following code:

```  
const readJson = require('read-package-json');
const Promise = require('bluebird');

const readJSON = Promise.promisify(readJson);

readJSON('./package.json', console.error, true)
    .then(response => {
        console.log(response);
    }); 

```

While the code above works and returns my package.json as an object, the problem is that the actual file path to my package.json is in ('../package.json'). Additionally, I've also tried running this without promises. I'm not sure if this is something that you have built in, but it seemed strange that this method would work for the incorrect file path but then not work for the correct one. Let me know!

**Comment by isaacs** [comment]
Can't reproduce this.  You realize that the path is relative to the cwd, not the module calling it?  Could that be the confusion?
