### ISSUE TITLE
[BUG] too slow

### ISSUE THREAD

**Issue by isaacs** [npm/read-package-json#82]
# What / Why

This module is too slow.  It does too much stuff, and much of it is unnecessary or inefficient.

## When

Running `npm ls` in a project with 2000 or more deps.

### Current Behavior

* It takes a really long time.

### Expected Behavior

* It should not take a really long time.

## Who
* @npm/cli-team 

## Proposal

Here's what it does today:

* If the `package.json` file can't be found, look for a magic comment in an `index.js` file instead.
* bundleDependencies - normalize the `bundledDependencies`/`bundleDependencies` key and value (this is fast and worthwhile).
* gypfile - glob for any file matching `*.gyp`, and if any are found, set `data.gypfile = true` and add an install script of `node-gyp rebuild`.
* serverjs - glob for a file named `server.js`, and if found, set `scripts.start` to `node server.js`
* scriptpath - strip `./node_modules/.bin` from the start of any scripts
* authors - Read a file named `AUTHORS` and add the contents to `data.contributors`
* readme - Glob for a file named `README.*`.  Save the file name as `data.readmeFilename`, and the data as `data.readme`.
* mans - If there is a `data.directories.man`, then glob in it for files named `*.[0-9]` and add the list to `data.man`.
* bins - Same as `mans`, but for `data.directory.bin`.  Also turns `"bin": [array, of, scripts]` into a proper object.
* githead - Read the file at `.git/HEAD` and save the shasum as `data.githead`.
* assign `data._id` as the `name@version`
* Make sure that all the `bin` references exist
* call `normalize-package-data` on the data, which again fixes a couple of things on the list above, but mostly just enforces various data type constraints.

Here's what I intend to make it do:

* Drop the `indexjs` stuff.  It's dumb and no one uses it.
* Keep the `bundleDeps`, script `./node_modules/.bin` path checking, and other basic data-checking normalizing stuff, but refactor it so that it's not calling a bunch of functions with constructed strings, as that seems like it prevents some of v8's optimizations.
* Drop `githead` entirely.
* We should handle the `directories.*` stuff when installing and linking a package, not when reading the json.  Drop it from here.
* Drop all the readme/readmeFilename stuff.
* Don't warn if a name/version/etc are missing.  It's kind of noisy and annoying to be nagged about adding a version to a package that is never going to be published.  We should just require that at publish time.

Just monkeypatching this module with something that does a simple `JSON.parse(fs.readFile(..))` brought it from this:

```
$ time node ../npm/arborist/la.js .

real	0m2.081s
user	0m2.875s
sys	0m0.642s
```

to this:

```
$ time node ../npm/arborist/la.js .

real	0m0.649s
user	0m0.830s
sys	0m0.253s
```

(`la.js` is a script that loads an actual tree and prints it, but doesn't do anything else.)

**Comment by isaacs** [comment]
Also, this module should really have some aggressive benchmarking/profiling around it.  We call it a _lot_ when reading package trees.

**Comment by lukekarrys** [comment]
https://github.com/npm/read-package-json-fast 😄
