### ISSUE TITLE
[QUESTION] Version 2.1.1 dropped support for Node v4.x, is it expected?

### ISSUE THREAD

**Issue by 7sDream** [npm/read-package-json#88]
# What / Why

I 'm using the `read-installed` package with locked version `4.0.3`, but `read-installed` itself don't has an package-lock.json(in version 4.0.3) and use `read-package-json: ^2.0.0`.

`read-package-json` version 2.1.1 add dep package `npm-normalize-package-bin`, there are `object destructring` syntax in it, which not supported by Node 4.x by default.

So my CI failed on Node 4.x due to the deps chain: 

```text
MyAppliation -> read-installed 4.0.3(locked) -> read-package-json ^2.0.0(no lock)

read-package-json 2.1.0 -> OK
read-package-json 2.1.1 -> npm-normalize-package-bin 1.0.0(locked) -> Fail
```

# Question

Is this breaking change expected?

Can we make it 3.0.0?

**Comment by christianbundy** [comment]
Also: could we get someone to publish that the npm-normalize-package-bin on GitHub? It's currently a private repo.

https://github.com/npm/npm-normalize-package-bin

**Comment by lukekarrys** [comment]
Cleaning out old/outdated issues in this repo 👋🏼

**Comment by ljharb** [comment]
@lukekarrys this is old, but it's still not resolved - the v2 line still has a breaking change in it. It'd still be nice to fix.
